spring:
    application:
        name: springarch
    jpa:
        show-sql: true

app:
    config:
        variable: variable value = X
        value: 500
        email: testing@gmail.com
        password: pass1234